Cherry pick of 9e7c686ebf2938c51f103e937aec292637d08921 failed
stdout:
Auto-merging academic/views/res_partner_views.xml
CONFLICT (content): Merge conflict in academic/views/res_partner_views.xml
Auto-merging academic/models/res_partner_link.py

stderr:
16:18:35.926758 git.c:444               trace: built-in: git cherry-pick 9e7c686ebf2938c51f103e937aec292637d08921
error: could not apply 9e7c686... [ADD] academic_sale_subscription: add new module
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: